### ISSUE TITLE
Request error: 429 Client Error: Too Many Requests for url:

### ISSUE THREAD

**Issue by shubhamsharmaPlanify** [SSujitX/google-news-url-decoder#10]
HI, I am facing issue, some times this code successfully gives decoded Url , but most of the times it gives Request error: 429 Client Error: Too Many Requests for url: this error, below is my function

def google_link_format(source_url):
    interval_time = 20
    try:
        decoded_url = new_decoderv1(source_url, interval=interval_time)
        if decoded_url.get("status"):
            return decoded_url.get("decoded_url", source_url)
        else:
            return source_url
    except Exception as e:
        print(f"Error occurred: {e}")
        return source_url
        
       I also tried sleep() to expand time between requests but nothing happen

**Comment by SSujitX** [comment]
#3 issue is already open. You can share. There is no need to create a new problem. Thanks. We are trying to work around the 429 error.
