### ISSUE TITLE
Unable to decode

### ISSUE THREAD

**Issue by ruthvik92** [SSujitX/google-news-url-decoder#4]
Hi,
I can't seem to decode this link:
I see that you're looking for `articles` in the decode script. 

news.google.com/read/CBMigwFBVV95cUxNSTdJdTY3SnlJSDJkLVNQN2NWZzVId3lJQzl4Q194OVJUcVB5Snlwa1dVUmpXaEYzbGdiZVBlVmRvdVEtcVM1c3JCYW95QXRxc1pGRzhYcTJ4S2k1bGxwY19TYS0tUkxqY2YyaE5PMHlUMV9Na3VHWmdoVHpPQWtnb1hfMA?hl=en-US&gl=US&ceid=US%3Aen

**Comment by SSujitX** [comment]
@ruthvik92 

**change this too news.google.com/read > https://news.google.com/rss/articles/ so link will be - https://news.google.com/rss/articles/CBMigwFBVV95cUxNSTdJdTY3SnlJSDJkLVNQN2NWZzVId3lJQzl4Q194OVJUcVB5Snlwa1dVUmpXaEYzbGdiZVBlVmRvdVEtcVM1c3JCYW95QXRxc1pGRzhYcTJ4S2k1bGxwY19TYS0tUkxqY2YyaE5PMHlUMV9Na3VHWmdoVHpPQWtnb1hfMA**

**Comment by SSujitX** [comment]
@ruthvik92 

change this too news.google.com/read > https://news.google.com/rss/articles/ so link will be - https://news.google.com/rss/articles/CBMigwFBVV95cUxNSTdJdTY3SnlJSDJkLVNQN2NWZzVId3lJQzl4Q194OVJUcVB5Snlwa1dVUmpXaEYzbGdiZVBlVmRvdVEtcVM1c3JCYW95QXRxc1pGRzhYcTJ4S2k1bGxwY19TYS0tUkxqY2YyaE5PMHlUMV9Na3VHWmdoVHpPQWtnb1hfMA
