### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by moehmeni** [SSujitX/google-news-url-decoder#8]
Hi thanks for your helpful package.
I used decoderv4 for this list:
```python
urls = ['https://news.google.com/rss/articles/CBMijAFBVV95cUxPX2gtRFd3ZXdiZGhueDVwWDJNUkg3eXhoRmloeE9kekpMaEJLckJENlBHYllvQ0JweGpQRDFKU3c0OFJ0Rno1eWxyM3NkblBKXzc2ZFpJWmYtSDdlSHNhUGVNSTdDcW1sR25fVEl4cGlhQW9xaWRWSmUxNFRLN1U2Rzc2RVFVSldLZFpncg?oc=5', 'https://news.google.com/rss/articles/CBMiyAFBVV95cUxOT1RUSGhNRnRETmVPUG9MWS0xcDY0N0tWc0xfMDRuWlhtSzhUSTFrUXJreVJqT2hQbzNOeDEtUFVkRlBfZmZyaGNTaG5fMl9acmFOMDlfYy1nLXluTUlZeXpfVnhXcHNZYnc4V1BrS3Q5ZmhBLXViaDUtOGVaMm11SEptbXloYUN1TXVXaW1aNkhvVUx5RkJXUml4RFVPWWNsSXNYRWUtRm9zdDNrNkcySXdRaU1fUks4a1lsUUZVOEhkWWQ4ekw2ZA?oc=5', 'https://news.google.com/rss/articles/CBMiwAFBVV95cUxONGpFaTY1dlh4MGdaNnZBUHVDcGVsV2V6aVJXbkFEVTZIaVlBZFh6TUNwYnAycGZlX01SejdWSjBBTUY1bklPZ2s2UnFuVmFCLTlaU0tLdFRnOEZqZFdwVWREVWpGNDEzTnQ5ZlV0NXlTbGpXZFk2cmlwZEx0TGRFMU9sOF9iVGxhM2drbTV6Sm5mN2tzbzRfQTY4bGs5VTNCdWY4LVdpMjI0Qk0zWmZIMHppSE85UkU3ZWNURExHVFE?oc=5']
```
but it returns [].
also I tried using decoderv2 and v3 and they respond with 
```
  File "/Users/momenim/Documents/news-benchmark/venv/lib/python3.9/site-packages/googlenewsdecoder/decoderv2.py", line 69, in decode_google_news_url
    return fetch_decoded_batch_execute(base64_str)
  File "/Users/momenim/Documents/news-benchmark/venv/lib/python3.9/site-packages/googlenewsdecoder/decoderv2.py", line 32, in fetch_decoded_batch_execute
    raise Exception(f"Header not found in response: {text}")
Exception: Header not found in response: )]}'

[["wrb.fr","Fbv4je",null,null,null,[3],"generic"],["di",15],["af.httprm",14,"6693785459577090755",0]]
```

**Comment by SSujitX** [comment]
> Hi thanks for your helpful package. I used decoderv4 for this list:
> 
> ```python
> urls = ['https://news.google.com/rss/articles/CBMijAFBVV95cUxPX2gtRFd3ZXdiZGhueDVwWDJNUkg3eXhoRmloeE9kekpMaEJLckJENlBHYllvQ0JweGpQRDFKU3c0OFJ0Rno1eWxyM3NkblBKXzc2ZFpJWmYtSDdlSHNhUGVNSTdDcW1sR25fVEl4cGlhQW9xaWRWSmUxNFRLN1U2Rzc2RVFVSldLZFpncg?oc=5', 'https://news.google.com/rss/articles/CBMiyAFBVV95cUxOT1RUSGhNRnRETmVPUG9MWS0xcDY0N0tWc0xfMDRuWlhtSzhUSTFrUXJreVJqT2hQbzNOeDEtUFVkRlBfZmZyaGNTaG5fMl9acmFOMDlfYy1nLXluTUlZeXpfVnhXcHNZYnc4V1BrS3Q5ZmhBLXViaDUtOGVaMm11SEptbXloYUN1TXVXaW1aNkhvVUx5RkJXUml4RFVPWWNsSXNYRWUtRm9zdDNrNkcySXdRaU1fUks4a1lsUUZVOEhkWWQ4ekw2ZA?oc=5', 'https://news.google.com/rss/articles/CBMiwAFBVV95cUxONGpFaTY1dlh4MGdaNnZBUHVDcGVsV2V6aVJXbkFEVTZIaVlBZFh6TUNwYnAycGZlX01SejdWSjBBTUY1bklPZ2s2UnFuVmFCLTlaU0tLdFRnOEZqZFdwVWREVWpGNDEzTnQ5ZlV0NXlTbGpXZFk2cmlwZEx0TGRFMU9sOF9iVGxhM2drbTV6Sm5mN2tzbzRfQTY4bGs5VTNCdWY4LVdpMjI0Qk0zWmZIMHppSE85UkU3ZWNURExHVFE?oc=5']
> ```
> 
> but it returns []. also I tried using decoderv2 and v3 and they respond with
> 
> ```
>   File "/Users/momenim/Documents/news-benchmark/venv/lib/python3.9/site-packages/googlenewsdecoder/decoderv2.py", line 69, in decode_google_news_url
>     return fetch_decoded_batch_execute(base64_str)
>   File "/Users/momenim/Documents/news-benchmark/venv/lib/python3.9/site-packages/googlenewsdecoder/decoderv2.py", line 32, in fetch_decoded_batch_execute
>     raise Exception(f"Header not found in response: {text}")
> Exception: Header not found in response: )]}'
> 
> [["wrb.fr","Fbv4je",null,null,null,[3],"generic"],["di",15],["af.httprm",14,"6693785459577090755",0]]
> ```

Yes, I am aware of that. Hoping we can fix the issue.

**Comment by SSujitX** [comment]
#7 The problem has been resolved.
